### ISSUE TITLE
Buffer error

### ISSUE THREAD

**Issue by xarvel** [kuzyk/gulp-rigger#4]
buffer.js:68
    throw new TypeError('must start with number, buffer, array or string');
          ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:68:11)
    at /home/user/testproject/node_modules/gulp-rigger/index.js:20:29
    at Rigger.<anonymous> (/home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/index.js:719:9)
    at Rigger.emit (events.js:107:17)
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/index.js:252:16
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/node_modules/async/lib/async.js:232:13
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/node_modules/async/lib/async.js:113:21
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/node_modules/async/lib/async.js:24:16
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/node_modules/async/lib/async.js:229:17
    at /home/user/testproject/node_modules/gulp-rigger/node_modules/rigger/index.js:391:21

**Comment by maroon775** [comment]
@xarvel  , how you solved this problem ?

**Comment by xarvel** [comment]
@maroon775 , problem was in incorrect path to include file.

**Comment by maroon775** [comment]
@xarvel , Thank you very much for reply. You made my day :)

**Comment by Postnov** [comment]
Also the problem can be, if in a file scss to connect css a file, that is different extensions of files. I wanted to ask whether there is a way to catch errors and prevent the failure of the main task when an error occurs in the rigger oparations. Gulp-nofity did not solve the problem.
P.S Forgive Google translator for his English :)
